name = "Hello World"
description = "This is my first Project for devoloping android app with python"
version = "0.0.1"
terminal = false
packages = [
    "/static/wheels/helloworld-0.0.1-py3-none-any.whl",
    "/static/wheels/toga_core-0.3.1-py3-none-any.whl",
    "/static/wheels/toga_web-0.3.1-py3-none-any.whl",
    "/static/wheels/travertino-0.3.0-py3-none-any.whl",
]

[splashscreen]
autoclose = true
